title: "Mateus Musto Pizini"
description: "Desenvolvedor · Progamador · APIs"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

author:
  name: "Mateus Musto Pizini"
  role: "Dev Full-Stack Júnior"
  email: "m.pizini@gmail.com"
  avatar_url: "https://i.imgur.com/CNnL6G9.jpeg"

collections:
  projects:
    output: true
