title: "Seu Nome"
description: "Desenvolvedor Front-end Júnior · React · APIs"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

author:
  name: "Seu Nome"
  role: "Dev Front-end Júnior"
  email: "seuemail@email.com"
  avatar_url: "https://link-da-sua-foto.webp"

collections:
  projects:
    output: true
