title: "Mateus Musto Pizini"
description: "Desenvolvedor Front-end Júnior · React · APIs"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

author:
  name: "Mateus Musto Pizini"
  role: "Desenvolvedor Front-end Júnior"
  email: "m.pizini@gmail.com"
  avatar_url: "https://link-da-sua-foto.webp"

collections:
  projects:
    output: true
