title: "Mateus Musto Pizini"
description: "Desenvolvedor Front-end Júnior · React · APIs"
# Tema oficial do GitHub Pages (leve, sleek)
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# Dados do autor (usado em includes/layouts)
author:
  name: "Mateus Musto Pizini"
  role: "Dev Front-end Júnior"
  email: "m.pizini@gmail.com"
  avatar_url: "https://via.placeholder.com/160" # troque por sua foto

# Coleção de projetos (opcional)
collections:
  projects:
    output: true

# Navegação (opcional)
nav:
  - title: Início
    url: /
  # - title: Projetos
  #   url: /#projetos

# Build
markdown: kramdown
kramdown:
  input: GFM
